[[redirects]]
  from = "/iar"
  to = "https://forms.gle/nvBai6qjzprhYmhp8"
  status = 302
  force = true

[[redirects]]
  from = "/iamremarkable"
  to = "https://forms.gle/nvBai6qjzprhYmhp8"
  status = 302
  force = true

[[redirects]]
  from = "/RoadToIWD"
  to = "https://forms.gle/oz9ucatgXPQtuDZV9"
  status = 302
  force = true

[[redirects]]
  from = "/IWDLatam21"
  to = "https://gdg.community.dev/events/details/google-gdg-buenos-aires-presents-iwd-latam-2021-international-womens-day/#/"
  status = 302
  force = true
